CREATE TABLE `stats` (
    id INT PRIMARY KEY,
    smallfry INT DEFAULT 0,
    chum INT DEFAULT 0,
    cohock INT DEFAULT 0,
    big_shot INT DEFAULT 0,
    drizzler INT DEFAULT 0,
    fish_stick INT DEFAULT 0,
    flipper_flopper INT DEFAULT 0,
    flyfish INT DEFAULT 0,
    maws INT DEFAULT 0,
    scrapper INT DEFAULT 0,
    steel_eel INT DEFAULT 0,
    steelhead INT DEFAULT 0,
    stinger INT DEFAULT 0,
    goldie INT DEFAULT 0,
    coho INT DEFAULT 0,
    boris INT DEFAULT 0
)